theme: jekyll-theme-minimal
title: Sophia Lynsky UO CIT Minor Portfolio
description: This page is a portfolio of the work I have completed while earning my computer and information technology minor at the University of Oregon.
